version: "3.7"

services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    # restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./server:/app
    environment:
      NODE_ENV: development
      PORT: 3001
      MYSQL_DATABASE: reusables
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    command: sh -c "npx prisma migrate dev --name init && npm run dev"
  mysql:
    image: mysql:5.7.13
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 10
    # volumes:
    #   - ./mysql:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always